questions = [
    "Beasiswa apa saja ada di undiksha?",
    "Apa syarat untuk mendaftar KIP Kuliah?",
    "Saya ingin tahu terkait dengan Beasiswa Afirmasi Dikti (Adik) Papua",
    "Berapa Daya Tampung Mahasiswa Baru Undiksha Tahun Akademik 2024/2025",
    "Berapa daya tampung mahasiswa program studi ilmu komputer s1?",
    "Daya tampung prodi matematika S1 berapa?",
    "Siapa saja yang boleh ikut SMBJM Undiksha?",
    "Kemana bisa mengadu jika saya punya permasalahan spesifik terkait SMBJM yang tidak saya pahami?",
    "Dimana bisa melihat data NISN?",
    "Fasilitas apa saja yang dimiliki undiskha?",
    "Berikan saya informasi tentang fasilitas laboratorium undiksha",
    "Dimana saya bisa mendapatkan informasi fasilitas layanan konseling?",
    "Apa visi misi FBS?",
    "Siapa Dekan Fakultas Bahasa dan Seni?",
    "Berikan informasi tentang Fakultas Bahasa dan Seni",
    "Siapa nama Wakil Dekan I Fakultas Ekonomi (FE)?",
    "Prodi apa saja yang ada di FE?",
    "Video profil FE",
    "Info tentang Fakultas Ekonomi dong",
    "Fakultas Ekonomi punya video profil?",
    "Siapa saja pimpinan Fakultas Hukum dan Ilmu Sosial (FHIS)?",
    "Siapa nama Dekan Fakultas Ilmu Pendidikan (FIP)?",
    "Kapan Fakultas Ilmu Pendidikan (FIP) Universitas Pendidikan Ganesha mulai berdiri dan apa jurusan awalnya?",
    "Video profil FIP",
    "Kapan Fakultas Kedokteran (FK) Universitas Pendidikan Ganesha didirikan?",
    "Apa visi dari Fakultas Kedokteran (FK)?",
    "Siapa nama Dekan Fakultas Kedokteran (FK) Universitas Pendidikan Ganesha?",
    "Apa visi dari Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA)?",
    "Siapa Dekan Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA) Universitas Pendidikan Ganesha?",
    "Sebutkan salah satu program studi yang ada di Jurusan Biologi dan Perikanan Kelautan di FMIPA",
    "Kapan program studi Pendidikan Olahraga dan Kesehatan pertama kali berdiri di bawah Jurusan Pendidikan Matematika dan Ilmu Pengetahuan Alam (MIPA)?",
    "Apa visi dari Fakultas Olahraga dan Kesehatan (FOK)?",
    "Siapa yang menjabat sebagai Dekan Fakultas Olahraga dan Kesehatan (FOK)?",
    "Kapan Fakultas Teknik dan Kejuruan (FTK) Universitas Pendidikan Ganesha mulai berdiri dan program studi awal apa yang ditawarkan?",
    "Apa visi dari Fakultas Teknik dan Kejuruan (FTK)?",
    "Siapa Dekan Fakultas Teknik dan Kejuruan (FTK)?",
    "Kapan periode pendaftaran untuk Jalur Seleksi Nasional Berbasis Prestasi (SNBP)?",
    "Kapan pengumuman hasil SNBT 2024 akan diumumkan?",
    "Kapan periode pendaftaran kembali untuk Jalur Seleksi Mandiri (SMBJM) Program Pascasarjana Gelombang 1?",
    "Apa dasar pengembangan kurikulum Undiksha?",
    "Apa saja jenis kecerdasan yang dikembangkan dalam kurikulum Undiksha berdasarkan falsafah Tri Hita Karana?",
    "Bagaimana kurikulum Undiksha dievaluasi?",
    "Kapan masa sanggah untuk calon mahasiswa yang dinyatakan lulus melalui jalur SMBJM dengan Skor UTBK-SNBT dan Prestasi?",
    "Apa yang harus dilakukan calon mahasiswa setelah mencetak kwitansi pembayaran UKT?",
    "Apa yang terjadi jika calon mahasiswa tidak mendaftar kembali sampai dengan tanggal 21 Juli 2024?",
    "Kapan pengumuman kelulusan untuk calon mahasiswa jalur SMBJM-CBT diumumkan?",
    "Apa yang terjadi jika calon mahasiswa tidak mendaftar kembali sampai dengan tanggal 6 Agustus 2024?",
    "Bagaimana calon mahasiswa dapat mencetak Nomor Induk Mahasiswa (NIM)?",
    "Kapan tahap pengisian data UKT untuk calon mahasiswa jalur SNBP dimulai dan berakhir?",
    "Apa saja berkas yang perlu disiapkan oleh calon mahasiswa untuk pengisian form data UKT secara online?",
    "Kapan masa sanggah untuk jalur SNBP dilaksanakan?",
    "Kapan periode pengisian form data UKT untuk calon mahasiswa jalur SNBT di Universitas Pendidikan Ganesha?",
    "Apa yang harus dilakukan calon mahasiswa setelah melakukan pembayaran UKT?",
    "Apa yang terjadi jika calon mahasiswa tidak mendaftar kembali sampai tanggal 30 Juni 2024?",
    "Apa visi dari Fakultas Pascasarjana Universitas Pendidikan Ganesha?",
    "Siapa yang menjabat sebagai Direktur Pascasarjana Universitas Pendidikan Ganesha?",
    "Sebutkan dua program doktoral yang ditawarkan oleh Fakultas Pascasarjana Universitas Pendidikan Ganesha.",
    " Apa itu BRI Virtual Account (BRIVA) dalam konteks pembayaran UKT di Universitas Pendidikan Ganesha?",
    "Bagaimana sifat dari sistem pembayaran BRI Virtual Account (BRIVA)?",
    "Di mana informasi lebih lanjut mengenai prosedur pembayaran UKT dengan BRIVA dapat ditemukan?",
    "Kapan jadwal pendaftaran untuk Seleksi Mandiri (SMBJM) Program Pascasarjana Gelombang 1?",
    "Apa yang harus dilakukan peserta Seleksi Mandiri jalur CBT setelah mendapatkan kode BRIVA?",
    "Apakah peserta jalur SNBP yang lolos namun tidak mendaftar kembali memenuhi syarat mengikuti jalur SMBJM?",
    "Kapan pendaftaran SNBP 2024 dilakukan?",
    "Apa syarat bagi siswa yang ingin mengikuti seleksi SNBP?",
    "Apa syarat sekolah untuk mengikutsertakan siswa dalam SNBP 2024?",
    "Kapan pelaksanaan UTBK Gelombang 1 untuk SNBT 2024?",
    "Apa saja materi yang diujikan dalam UTBK 2024?",
    "Berapa biaya pendaftaran UTBK-SNBT 2024?",
    "Apa fungsi utama Unit Kegiatan Mahasiswa (UKM) di Universitas Pendidikan Ganesha?",
    "Apa sifat dari Unit Kegiatan Mahasiswa (UKM) di Universitas Pendidikan Ganesha?",
    "Di mana mahasiswa dapat mengakses informasi lebih lanjut tentang UKM di Undiksha?",
    "Apa tugas utama dari UPA TIK Universitas Pendidikan Ganesha?",
    "Siapa kepala UPA TIK Universitas Pendidikan Ganesha saat ini?",
    "Sebutkan beberapa layanan utama yang disediakan oleh UPA TIK Undiksha",
    "Apa nama lengkap Undiksha?",
    "Di mana lokasi Universitas Pendidikan Ganesha?",
    "Apa motto Universitas Pendidikan Ganesha?",
    "Siapa kepala UPA TIK Universitas Pendidikan Ganesha?",
    "Apa akreditasi yang dimiliki Universitas Pendidikan Ganesha?",
    "Sejak tahun berapa Universitas Pendidikan Ganesha berubah status menjadi universitas?",
    "Apa visi Universitas Pendidikan Ganesha?",
    "Apa misi Universitas Pendidikan Ganesha?",
    "Apa tujuan utama Universitas Pendidikan Ganesha?",
    "Sebutkan fakta penting tentang Universitas Pendidikan Ganesha.",
    "Apa yang menjadi acuan dalam pelaksanaan kegiatan di Universitas Pendidikan Ganesha?",
    "Apa yang dimaksud dengan KIP Kuliah?",
    "Siapa rektor Universitas Pendidikan Ganesha saat ini?",
    "Apakah ada program studi yang dibuka di denpasar?",
    "Apa saja jalur penerimaan mahasiswa baru di Universitas Pendidikan Ganesha?",
    "Apa syarat umum untuk mendaftar di Universitas Pendidikan Ganesha?",
    "Bagaimana cara mendaftar di Universitas Pendidikan Ganesha?",
    "Apa jenis program pendidikan yang ditawarkan oleh Universitas Pendidikan Ganesha?",
    "Apa itu program sarjana terapan (D4)?",
    "Sebutkan dua fakultas tentang teknik dan tentang olahraga yang ada di Universitas Pendidikan Ganesha!",
    "Apa yang dimaksud dengan UKT di Universitas Pendidikan Ganesha?",
    "Sebutkan beberapa fasilitas yang ditawarkan Universitas Pendidikan Ganesha.",
    "Apa tujuan dari program KIP Kuliah?",
    "Apa yang dimaksud dengan Tri Hita Karana dalam konteks Universitas Pendidikan Ganesha?",
    "Apa prestasi yang telah diraih Universitas Pendidikan Ganesha dalam bidang akreditasi?"
]


ground_truths = [
    
]