services:
  api:
    build: .
    command: sh -c "uvicorn api.api:app --reload --port 4001 --host=0.0.0.0 --no-date-header"
    env_file:
      - .env
    ports:
      - "4001:4001"
    volumes:
      - .:/app
